# Generated by Django 5.0.10 on 2025-02-04 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbots", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExecutionModelTime",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=255)),
                ("pregunta", models.TextField(blank=True, null=True)),
                ("respuesta", models.TextField(blank=True, null=True)),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
              
            ],
        ),
    ]
