# Generated by Django 5.0.10 on 2025-02-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbots", "0002_executionmodeltime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="executionmodeltime",
            old_name="end_time",
            new_name="date",
        ),
        migrations.RemoveField(
            model_name="executionmodeltime",
            name="start_time",
        ),
        migrations.AddField(
            model_name="executionmodeltime",
            name="time",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
