# Generated by Django 5.0.10 on 2025-02-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbots", "0003_rename_end_time_executionmodeltime_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="executionmodeltime",
            name="date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
