# Generated by Django 5.0.10 on 2025-02-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbots", "0004_alter_executionmodeltime_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=254)),
                ("telegram_id", models.CharField(max_length=25)),
            ],
        ),
    ]
