# Generated by Django 5.0.10 on 2025-02-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbots", "0005_useradmin"),
    ]

    operations = [
        migrations.CreateModel(
            name="Models",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("max_new_tokens", models.DecimalField(decimal_places=2, max_digits=5)),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                ("top_k", models.DecimalField(decimal_places=2, max_digits=5)),
                ("top_p", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "repetition_penalty",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
            ],
        ),
    ]
