# Generated by Django 5.0.10 on 2025-02-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbots", "0006_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="executionmodeltime",
            name="parameters",
            field=models.TextField(blank=True, null=True),
        ),
    ]
