# Generated by Django 5.0.10 on 2025-02-24 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbots", "0007_executionmodeltime_parameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="models",
            name="API",
            field=models.BooleanField(default=False),
        ),
    ]
