# Generated by Django 5.0.10 on 2025-03-15 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbots", "0008_models_api"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="executionmodeltime",
            name="bug_report",
        ),
        migrations.RemoveField(
            model_name="executionmodeltime",
            name="good_feedback",
        ),
    ]
